# This is a basic workflow to help you get started with Actions

name: FSS-Automates-Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  #pull_request:
    #branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_id }}
          aws-region: us-east-1

      # Runs a single command using the runners shell
      - name: Run The fss-stack-deploy.sh script and Deploy the stack to your AWS Account
        run: ./fss-stack-deploy.sh
        env:
          externalid: ${{ secrets.externalid }}
          allinone_stackname: ${{ secrets.allinone_stackname }}
          region: ${{ secrets.region }}
          s3bucket_to_scan: ${{ secrets.s3bucket_to_scan }}
          c1_api_key: ${{ secrets.c1_api_key }}

      # - name: Where i am
      #   run: pwd
      
      # - name: List directory
      #   run: ls -lha

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
